import './globals.css';
import Header from './components/Header/index';
import Footer from './components/Footer/Footer';


export const metadata = {
  title: 'Marispect',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
